import os
import datetime
from typing import Dict, Any, List
from antigravity_core import Antigravity, DatasetSummary
from chart_engine import ChartEngine

class Opal:
    """
    The Brain / Orchestrator.
    Manages the workflow: Ingestion -> Analysis -> Insights -> Visualization -> Reporting.
    """
    def __init__(self):
        self.antigravity = Antigravity()
        self.chart_engine = ChartEngine()
        self.output_dir = "output"

    def generate_dummy_insights(self, summary: DatasetSummary, user_query: str = "") -> List[str]:
        """
        Simulates AI-generated insights based on summary stats.
        In a real production env, this would call GPT-4o with the summary json.
        """
        insights = []
        insights.append(f"Analyzed {summary.total_rows} rows across {len(summary.columns)} columns.")
        
        # Acknowledge User Query
        if user_query:
            insights.append(f"💡 **Focusing on User Query**: '{user_query}'")
            if "sales" in user_query.lower() and "Sales" in summary.numeric_stats:
                insights.append("🔍 Deep dive: Sales data shows significant variance.")
            elif "satisfaction" in user_query.lower() and "Customer_Satisfaction" in summary.numeric_stats:
                insights.append("😊 Sentiment Analysis: Customer satisfaction is stable.")

        # Simple rule-based insight
        if any(v > 0 for v in summary.missing_values.values()):
            insights.append("⚠️ Data Quality Alert: Significant missing values detected in key columns.")
        
        # Numeric insights
        for col, stats in summary.numeric_stats.items():
            mean_val = stats.get('mean', 0)
            max_val = stats.get('max', 0)
            insights.append(f"📈 **{col}**: Average value is {mean_val:.2f}, peaking at {max_val}.")
            
        return insights

    def generate_report(self, summary: DatasetSummary, insights: List[str], charts: List[Dict]):
        """
        Compiles the findings into a Markdown report.
        """
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
        
        report_content = f"""# 📊 Automated Data Analysis Report
**Generated by Opal** at {timestamp}

## 1. Executive Summary
{insights[0]}

## 2. Key Insights
"""
        for i, insight in enumerate(insights[1:], 1):
            report_content += f"- {insight}\n"

        report_content += "\n## 3. Visual Analysis\n"
        
        for chart in charts:
            report_content += f"### {chart['title']}\n"
            report_content += f"{chart['description']}\n\n"
            # Embed HTML link or interactive component hint
            # Since markdown can't embed interactive JS easily without iframe, we link it or show fallback
            report_content += f"**[🔎 View Interactive Chart](charts/{chart['path'].replace('.json', '.html')})**\n\n"
            report_content += f"*(Chart spec available at `charts/{chart['path']}`)*\n\n"

        report_content += "\n## 4. Dataset Overview\n"
        report_content += f"- **Rows**: {summary.total_rows}\n"
        report_content += f"- **Columns**: {', '.join(summary.columns)}\n"
        
        if summary.issues:
            report_content += "\n### ⚠️ Data Issues Detected\n"
            for issue in summary.issues:
                report_content += f"- **{issue.column}**: {issue.description}\n"

        output_path = os.path.join(self.output_dir, "reports", "Analysis_Report.md")
        with open(output_path, 'w') as f:
            f.write(report_content)
        
        print(f"📄 Report generated at: {output_path}")
        return {
            "report_path": output_path,
            "report_content": report_content,
            "charts": charts,
            "summary": summary.dict()
        }

    def process_chat(self, file_path: str, user_message: str, history: List[Dict] = []) -> Dict[str, Any]:
        """
        Intelligent Router using Local LLM (Ollama).
        """
        if not self.antigravity.load_data(file_path):
             return {"type": "error", "message": "Could not access dataset."}

        # Lazy load to avoid startup error if Ollama offline
        from llm_client import LLMClient
        if not hasattr(self, 'llm_client'):
             # Default to llama3, but could be configurable
            self.llm_client = LLMClient() 

        summary = self.antigravity.analyze()
        schema = summary.columns # Dict of Col -> Type is needed, but analyze() returns DatasetSummary where columns is List[str]
        # We need types for the LLM to understand what to plot
        dtypes = {k: str(v) for k, v in self.antigravity.df.dtypes.items()}

        response = {"type": "text", "message": "", "charts": []}

    def process_chat(self, file_path: str, user_message: str) -> Dict[str, Any]:
        """
        Heuristic 'LLM' that routes user natural language to specific actions.
        """
        if not self.antigravity.load_data(file_path):
             return {"type": "error", "message": "Could not access dataset."}

        msg = user_message.lower()
        summary = self.antigravity.analyze()
        response = {"type": "text", "message": "", "charts": []}

    def process_chat(self, file_path: str, user_message: str, history: List[Dict] = []) -> Dict[str, Any]:
        """
        Intelligent Router using Local LLM (Ollama).
        """
        if not self.antigravity.load_data(file_path):
             return {"type": "error", "message": "Could not access dataset."}

        # Lazy load to avoid startup error if Ollama offline
        from llm_client import LLMClient
        if not hasattr(self, 'llm_client'):
            self.llm_client = LLMClient() # Default to llama3

        summary = self.antigravity.analyze()
        schema = summary.columns # Dict of Col -> Type is needed, currently summary.columns is list?
        # Let's get types
        dtypes = {k: str(v) for k, v in self.antigravity.df.dtypes.items()}

        response = {"type": "text", "message": "", "charts": []}
        
        # 1. Ask LLM
        llm_result = self.llm_client.query(user_message, dtypes, history)
        
        # 2. Parse Result
        if llm_result.get("type") == "chart":
            spec = llm_result.get("spec")
            # Inject data into spec (Vega-Lite needs 'values')
            # For performance, we sample if data > 5000 rows
            data_sample = self.antigravity.df.sample(min(5000, len(self.antigravity.df))).to_dict(orient='records')
            spec["data"] = {"values": data_sample}
            
            response["type"] = "chart"
            response["message"] = llm_result.get("message", "Here is the visualization you requested.")
            response["charts"].append(spec)
            
        elif llm_result.get("type") == "analysis":
             response["message"] = llm_result.get("content")
             
        elif llm_result.get("type") == "error":
             response["message"] = llm_result.get("message")
        
        else:
             response["message"] = "I analyzed the data but wasn't sure how to visualize it. Try being more specific!"

        return response
            
        return response

        return response

    def export_tableau(self, file_path: str) -> Dict[str, str]:
        """
        Generates a Tableau Data Source file for the dataset.
        """
        if not self.antigravity.load_data(file_path):
             return {"error": "Could not access dataset."}

        from tableau_connector import TableauConnector
        connector = TableauConnector()
        
        # Ensure output dir exists
        export_dir = os.path.join(self.output_dir, "exports")
        os.makedirs(export_dir, exist_ok=True)
        
        dtypes = {k: str(v) for k, v in self.antigravity.df.dtypes.items()}
        tds_path = connector.create_tableau_package(file_path, dtypes, export_dir)
        
        return {"path": tds_path, "filename": os.path.basename(tds_path)}

    def run_pipeline(self, file_path: str, user_query: str = "", x_axis: str = None, y_axis: str = None) -> Dict[str, Any]:
        """Runs the pipeline and returns the result."""
        print(f"💎 Opal: Starting analysis on {file_path} with query: '{user_query}'")
        
        # 1. Ingestion & Analysis
        if not self.antigravity.load_data(file_path):
            return {"error": "Pipeline failed at data loading."}

        summary = self.antigravity.analyze()
        print("✅ Analysis Complete.")

        # 2. Insight Generation
        insights = self.generate_dummy_insights(summary, user_query)
        
        # Add Trend Insight if y_axis is selected
        if y_axis:
            trend_insight = self.antigravity.calculate_trend(y_axis)
            if trend_insight:
                insights.append(f"🔮 **Predictive Insight**: {trend_insight}")

        # 3. Chart Generation
        generated_charts = []
        
        # If user specified axes, prioritize that chart
        if x_axis and y_axis:
            print(f"🎨 Generating Custom Chart: {x_axis} vs {y_axis}")
            # Determine best chart type
            is_y_numeric = y_axis in summary.numeric_stats
            
            if is_y_numeric:
                chart_spec = self.chart_engine.create_bar_chart(
                    self.antigravity.df.head(50), # Cap for performance
                    x_col=x_axis,
                    y_col=y_axis,
                    title=f"Custom Analysis: {y_axis} by {x_axis}"
                )
                chart_name = f"custom_chart_{y_axis}_by_{x_axis}.json"
                chart_path = os.path.join(self.output_dir, "charts", chart_name)
                self.chart_engine.save_chart_json(chart_spec, chart_path)
                self.chart_engine.save_chart_html(chart_spec, chart_path.replace('.json', '.html'))
                
                generated_charts.append({
                    "title": "Custom Analysis",
                    "path": chart_name,
                    "description": f"User selected visualization of **{y_axis}** by **{x_axis}**.",
                    "spec": chart_spec
                })

        # Fallback/Additional numeric charts (existing logic)
        numeric_cols = list(summary.numeric_stats.keys())
        if len(numeric_cols) >= 1 and not (x_axis and y_axis):
             # Only generate default if no custom chart, or add as secondary?
             # Let's add default logic as simplified "Overview" if no custom chart
             pass 
             
        # Always generate the default scatter if we have enough numeric cols and no specific override that conflicts
        if len(numeric_cols) >= 2 and (not generated_charts or len(generated_charts) < 2):
             target_col = numeric_cols[0]
             y_col = numeric_cols[1]
             # Check if we already plotted this
             if not (x_axis == target_col and y_axis == y_col):
                scatter_spec = self.chart_engine.create_scatter_plot(
                    self.antigravity.df.sample(min(100, len(self.antigravity.df))),
                    x_col=target_col,
                    y_col=y_col,
                    title=f"Correlation Overview: {target_col} vs {y_col}"
                )
                scatter_name = f"scatter_{target_col}_vs_{y_col}.json"
                scatter_path = os.path.join(self.output_dir, "charts", scatter_name)
                self.chart_engine.save_chart_json(scatter_spec, scatter_path)
                self.chart_engine.save_chart_html(scatter_spec, scatter_path.replace('.json', '.html'))

                generated_charts.append({
                     "title": "Correlation Overview",
                     "path": scatter_name,
                     "description": f"Exploring relationship between {target_col} and {y_col}.",
                     "spec": scatter_spec
                })

        # 4. Report Generation
        result = self.generate_report(summary, insights, generated_charts)
        print("✅ Opal: Pipeline finished successfully.")
        return result
